name: GHA Static Analyzer - Required Workflow

# Secrets are inherited from calling workflow within same org or enterprise
# For all other outside wortkflows
on:
  pull_request: {}

jobs:
  analyze-workflows:
    name: Analyze CI Workflows - ${{github.repository}}
    permissions:
      contents: read
      actions: read
      pull-requests: read
      # security-events: write # publish codeql results
    runs-on: ubuntu-latest
    steps:
      # Helps to run the scan on a local directory at the triggered ref
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
         token: ${{ github.token }}
         repository: ${{github.repository}}
         ref:  ${{github.ref}}
         path: ${{github.repository}}
         persist-credentials: false
      - name: Generate Metadata
        id: meta
        run: |
          SCAN_TIMESTAMP=$(date --utc +%Y%m%d_%H%M%S)
          echo "scan_timestamp=$SCAN_TIMESTAMP" >> "$GITHUB_OUTPUT"

          REPO_SLUG="${FULL_REPO_NAME//\//-}"

          if [[ "${{github.event_name}}" == "pull_request" ]]; then
            REF_SLUG="pr-${{github.event.pull_request.number}}"
          else
            REF_SLUG="${TARGET_SCAN_REF//\//-}"
          fi

          ASSET_PREFIX="report_${REPO_SLUG}_${REF_SLUG}_${SCAN_TIMESTAMP}"
          echo "REPO_SLUG=${REPO_SLUG}" >> "$GITHUB_OUTPUT"
          echo "REF_SLUG=${REF_SLUG}" >> "$GITHUB_OUTPUT"
          echo "ASSET_PREFIX=$ASSET_PREFIX" >> "$GITHUB_OUTPUT"
        env:
          FULL_REPO_NAME:  ${{github.repository}}
          TARGET_SCAN_REF: ${{github.ref}}
      - name: Check GH anti-pattern using zizmor
        id: zizmor
        uses: Kong/public-shared-actions/security-actions/scan-gh-workflows@21158ae3c9c2fdcb72c3fcedaf552e3f6007f05d # v4.1.2
        with:
          scan_path: ${{github.workspace}}/${{github.repository}}
          github_token: ${{ github.token }}
          asset_prefix: ${{ steps.meta.outputs.ASSET_PREFIX }}
          offline_audit_checks: ${{vars.ZIZMOR_OFFLINE_AUDIT_CHECKS || 'true'}}
          persona: ${{vars.ZIZMOR_PERSONA || 'regular'}}
          fail_on_findings: ${{vars.FAIL_ZIZMOR || 'false'}}
