name: GHA Static Analyzer - Required Workflow

# Secrets are inherited from calling workflow within same org or enterprise
# For all other outside wortkflows
on:
  pull_request: {}
  workflow_dispatch: {}

jobs:
  analyze-ci:
    name: Analyze CI - ${{github.repository}}
    permissions:
      contents: read
      actions: read
      pull-requests: read
      # security-events: write # publish codeql results
    uses: Kong/public-shared-actions/.github/workflows/gh-analyze.yml@feat/gh-anti-pattern-scan 
    with:
      TARGET_SCAN_REPOSITORY: ${{github.repository}}
      TARGET_SCAN_REF: ${{github.ref}}